spring.application.name=parsexml

# DB
spring.datasource.url=jdbc:postgresql://localhost:5433/parse_xml
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop

# API
spring.mvc.servlet.path=/api/v1

# APP
trixi.parse.xml.resource-url=https://www.smartform.cz/download/kopidlno.xml.zip

# ASYNC
trixi.xml.parsing.async.core-pool-size=2
trixi.xml.parsing.async.max-pool-size=8
trixi.xml.parsing.async.queue-capacity=10
